kind: pipeline
name: default

steps:
  - name: test
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    image: ruby
    commands:
      - bundle install --jobs=3 --retry=3
      - bundle exec rspec